
AWSTemplateFormatVersion: 2010-09-09

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  SecondBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Suspended
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
              # SSEAlgorithm: 'aws:kms'
              # KMSMasterKeyID: KMS-KEY-ARN


Outputs:
  s3arn:
    Value: !GetAtt
      - S3Bucket
      - Arn
    Description: Arn for website hosted on S3

  anotherArn:
    Value: !GetAtt
      - SecondBucket
      - WebsiteURL
    Description: Arn for website hosted on S3





