version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "first-s3-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1df8sc3szgcoq"
s3_prefix = "first-s3-sam"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "VersioningStatus=\"Enabled\""
